"""Signal quality validation: Information Coefficient, win-rate, and return profile.

Given a list of historical signal scores (generated by SignalEngine) and the
corresponding realised forward returns, compute standard quant metrics to judge
whether the signal has predictive power before deploying it live.

Usage
-----
::

    from libs.recommendations.signal_validator import validate_signal_quality

    result = validate_signal_quality(
        signal_scores=scores,          # list[float], e.g. output of SignalEngine
        forward_returns_1d=ret_1d,     # list[float] in parallel with scores
        forward_returns_5d=ret_5d,     # optional
    )
    print(result.ic_1d, result.win_rate_1d)
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Optional


@dataclass(frozen=True)
class SignalValidationResult:
    """Summary statistics for a historical signal backtest."""

    n_observations: int

    # Information Coefficient = Spearman rank correlation(signal, forward_return)
    ic_1d: Optional[float]      # 1-day forward IC
    ic_5d: Optional[float]      # 5-day forward IC

    # Win-rate = fraction of observations where sign(signal) == sign(return)
    win_rate_1d: Optional[float]
    win_rate_5d: Optional[float]

    # Average forward return when signal is positive (bullish)
    avg_return_when_positive_1d: Optional[float]
    avg_return_when_positive_5d: Optional[float]

    # Average forward return when signal is negative (bearish)
    avg_return_when_negative_1d: Optional[float]
    avg_return_when_negative_5d: Optional[float]

    # Long-short spread: avg(bull) - avg(bear)
    long_short_spread_1d: Optional[float]
    long_short_spread_5d: Optional[float]

    @property
    def is_useful_1d(self) -> bool:
        """True when 1-day IC > 0.03 and win-rate > 52%."""
        return (
            self.ic_1d is not None
            and self.ic_1d > 0.03
            and self.win_rate_1d is not None
            and self.win_rate_1d > 0.52
        )

    @property
    def is_useful_5d(self) -> bool:
        """True when 5-day IC > 0.03 and win-rate > 52%."""
        return (
            self.ic_5d is not None
            and self.ic_5d > 0.03
            and self.win_rate_5d is not None
            and self.win_rate_5d > 0.52
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _rank(values: list[float]) -> list[float]:
    """Return ranks (1-based, average ties) for a list of floats."""
    n = len(values)
    indexed = sorted(range(n), key=lambda i: values[i])
    ranks = [0.0] * n
    i = 0
    while i < n:
        j = i
        while j + 1 < n and values[indexed[j + 1]] == values[indexed[i]]:
            j += 1
        avg_rank = (i + j) / 2.0 + 1
        for k in range(i, j + 1):
            ranks[indexed[k]] = avg_rank
        i = j + 1
    return ranks


def _spearman_ic(x: list[float], y: list[float]) -> Optional[float]:
    """Spearman rank correlation coefficient, or None on degenerate input."""
    n = len(x)
    if n < 4:
        return None
    rx = _rank(x)
    ry = _rank(y)
    mean_rx = sum(rx) / n
    mean_ry = sum(ry) / n
    cov = sum((rx[i] - mean_rx) * (ry[i] - mean_ry) for i in range(n)) / n
    std_rx = math.sqrt(sum((v - mean_rx) ** 2 for v in rx) / n)
    std_ry = math.sqrt(sum((v - mean_ry) ** 2 for v in ry) / n)
    if std_rx == 0 or std_ry == 0:
        return None
    return cov / (std_rx * std_ry)


def _win_rate(signals: list[float], returns: list[float]) -> Optional[float]:
    """Fraction of observations where sign(signal) == sign(return)."""
    pairs = [(s, r) for s, r in zip(signals, returns) if s != 0.0]
    if not pairs:
        return None
    correct = sum(1 for s, r in pairs if (s > 0) == (r > 0))
    return correct / len(pairs)


def _avg_return_by_signal_sign(
    signals: list[float], returns: list[float], positive: bool
) -> Optional[float]:
    subset = [r for s, r in zip(signals, returns) if (s > 0) == positive and s != 0.0]
    if not subset:
        return None
    return sum(subset) / len(subset)


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def validate_signal_quality(
    signal_scores: list[float],
    forward_returns_1d: list[float],
    forward_returns_5d: Optional[list[float]] = None,
) -> SignalValidationResult:
    """Compute IC, win-rate, and return profiles for a historical signal.

    Parameters
    ----------
    signal_scores:
        Raw signal scores in [-1, 1] from :class:`SignalEngine.generate_signal`.
    forward_returns_1d:
        Realised 1-day-ahead returns aligned with *signal_scores*.
    forward_returns_5d:
        Optional 5-day-ahead returns.  Pass ``None`` to skip 5-day metrics.

    Returns
    -------
    :class:`SignalValidationResult`
    """
    if len(signal_scores) != len(forward_returns_1d):
        raise ValueError(
            f"signal_scores ({len(signal_scores)}) and forward_returns_1d "
            f"({len(forward_returns_1d)}) must have the same length."
        )
    if forward_returns_5d is not None and len(forward_returns_5d) != len(signal_scores):
        raise ValueError(
            f"forward_returns_5d length {len(forward_returns_5d)} != "
            f"signal_scores length {len(signal_scores)}"
        )

    n = len(signal_scores)
    ic_1d = _spearman_ic(signal_scores, forward_returns_1d)
    wr_1d = _win_rate(signal_scores, forward_returns_1d)
    avg_pos_1d = _avg_return_by_signal_sign(signal_scores, forward_returns_1d, True)
    avg_neg_1d = _avg_return_by_signal_sign(signal_scores, forward_returns_1d, False)
    ls_1d = (
        (avg_pos_1d - avg_neg_1d)
        if avg_pos_1d is not None and avg_neg_1d is not None
        else None
    )

    ic_5d = wr_5d = avg_pos_5d = avg_neg_5d = ls_5d = None
    if forward_returns_5d is not None:
        ic_5d = _spearman_ic(signal_scores, forward_returns_5d)
        wr_5d = _win_rate(signal_scores, forward_returns_5d)
        avg_pos_5d = _avg_return_by_signal_sign(signal_scores, forward_returns_5d, True)
        avg_neg_5d = _avg_return_by_signal_sign(signal_scores, forward_returns_5d, False)
        ls_5d = (
            (avg_pos_5d - avg_neg_5d)
            if avg_pos_5d is not None and avg_neg_5d is not None
            else None
        )

    return SignalValidationResult(
        n_observations=n,
        ic_1d=ic_1d,
        ic_5d=ic_5d,
        win_rate_1d=wr_1d,
        win_rate_5d=wr_5d,
        avg_return_when_positive_1d=avg_pos_1d,
        avg_return_when_positive_5d=avg_pos_5d,
        avg_return_when_negative_1d=avg_neg_1d,
        avg_return_when_negative_5d=avg_neg_5d,
        long_short_spread_1d=ls_1d,
        long_short_spread_5d=ls_5d,
    )
